version: "3"
services:
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/app
      - /app/node_modules 
    working_dir: /app
    tty: true
    command: npm run dev
